### ISSUE TITLE
Invalid request

### ISSUE THREAD

**Issue by ghajj** [akhan118/kiki#1]
I am getting 400 invalid request to the get_access_token function.
Any ideas?
Thanks,
Ghassan

**Comment by akhan118** [comment]
print(authReply)  and that will give you some clues.

**Comment by ghajj** [comment]
Thx. I had to go through the process of getting a code, token, and a
refresh token.
It then worked with the refresh token.

Mobile app, please excuse brevity.

**Comment by akhan118** [comment]
You are very welcome and glad you are finding the library useful .
