### ISSUE TITLE
Not able to query via TD API

### ISSUE THREAD

**Issue by BuddhaSmiles7** [akhan118/kiki#3]
Hi,
I tried the code posted at https://gist.github.com/akhan118/80a975a023e5acd8437fe25ec32c1a78/revisions to access TD Ameritrade but get the error 'Key error: access_token'.
I use the same refresh_token, api_key and client_id on the following webpage and am successfully able to generate an access token: https://developer.tdameritrade.com/authentication/apis/post/token-0

Can you have a look and suggest if  your code needs to be modified?

With Regards,

Anu

**Comment by BuddhaSmiles7** [comment]
My apologies, I did not realize an error in my code. Closing this issue.

**Comment by akhan118** [comment]
No worries, let me know if anything else comes up. ty
